name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    name: Lint clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format lint
        run: find . \( -name '*.[ch]pp' -o -name '*.h' -o -name '*.ino' \) | xargs clang-format --verbose --style=file -n --Werror
